name: 03 - workflow runner
on: push
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: show os
        run: echo "runner os $runner.os"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: show os
        run: echo "runner os $runner.os"