name: 06 - context
run-name: 06 - context | DEBUG - ${{inputs.debug}}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: "This is a sample variable"
  MY_OVERWRIDDEN_VAR: "This value will be overridden"
jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event Path: ${{ github.event_path }}"
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
          echo "GraphQL URL: ${{ github.graphql_url }}"
      - name: retrieve variable
        run: echo "variable value is ${{ vars.MY_VARIABLE }}"
