
name: 07 - Using Expression
run-name: 07 - Using Expression | DEBUG - ${{inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug: 
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] print start-up data'
        if: ${{ inputs.debug }}
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
      - name: '[debug] pront when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "I was trigerred from main"
      - name: Greetings
        run: echo "Hello World"