name: 08 - Using Variable

on:
  push:
  workflow_dispatch:
env:
    MY_WORKFLOW_VAR: "I am a MY_WORKFLOW_VAR"
    UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR  || 'default value' }}
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRIDDEN: 'I am a MY_OVERWRIDDEN_VAR'
    steps:
      - name: Print ENV Variable
        env:
          STEP_VAR: 'I am a step env var'
          step-var2: 'I am another step var'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var2: $step_var2"
          echo "job env var: $JOB_VAR"
          echo "workflow env var: $MY_WORKFLOW_VAR"
          echo "overriddne env var: $OVERWRIDDEN"
      - name: Overwrite Job Variable
        env:
          OVERWRIDDEN: 'I have been overriddne'
        run: |
          echo "step env var: ${{env.OVERWRIDDEN}}"
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: |
          echo "Org Var: ${{ vars.ORG_VAR }}"
          echo "Org OVERWRIDDEN var: ${{ vars.OVERWRITTEN_VAR }}"
          echo "Repo vars: ${{ vars.REPOSITORY_VAR }}"

  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Variable
        echo "Org Var: ${{vars.ORG_VAR}}"
        echo "Org OVERWRIDDEN var: ${{ vars.OVERWRITTEN_VAR }}"
        echo "Repo vars: ${{ vars.REPOSITORY_VAR }}"
        echo "Environment vars: ${{ vars.TARGET_VAR }}"

  echho-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined Variable
        run: |
          echo "Org var: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
